### ISSUE TITLE
在努比亚手机上没法上传文件，我自己整了下，解决了。

### ISSUE THREAD

**Issue by rmshadows** [CPPAlien/FileTransfer#10]
这个[版本](http://d.7short.com/transfer)的文件传输助手在我**nubia手机**上无法选择文件上传到电脑。因为**没法打开手机的文件浏览器**，_点击上传文件按钮 “+” 打开的却是手机通讯录_。

挺好的个玩意儿，想着一定是哪里出了小问题，第一次整安卓，不知道这样改在其他手机还能不能用，我对`FileTransfer/app/src/main/java/me/pengtao/filetransfer/MainActivity.java`中第125行做了少许修改：

*原代码：
            
                Intent intent = new Intent();
    
                intent.setAction(Intent.ACTION_GET_CONTENT);
                    
                intent.setType("*/*");
                    
                startActivityForResult(intent, FILE_FETCH_CODE);
    
    *修改为： 
    
                Intent intent = new Intent(Intent.ACTION_GET_CONTENT);

                intent.setType("*/*");

                intent.addCategory(Intent.CATEGORY_OPENABLE); //就是加了这句，其他没变
                    
                startActivityForResult(intent,FILE_FETCH_CODE);

--第一次发issue，如有不妥之处还望指正--

**Comment by CPPAlien** [comment]
可以发个 PR 哦
