### ISSUE TITLE
This project didn't work.

### ISSUE THREAD

**Issue by poorvajappja** [CPPAlien/FileTransfer#11]
I download this  app from play store .

I run this app in my computer's browser.

It didn't work. 

The older version works smoothly. 
But , master Version didn't work.

**Comment by palte5** [comment]
Ein Hauskaufen bringt halt immer seine Probleme! Ich würde mir dabei immer richtig viel Zeit nehmen. [https://www.ivd24immobilien.de/haus-kaufen/](url)

**Comment by poorvajappja** [comment]
Which language is this?
I can't understand. 
Can you send in English?

**Comment by CPPAlien** [comment]
Can you say how it didn't work clearly?

**Comment by poorvajappja** [comment]
It comes file fetch failed.

**Comment by CPPAlien** [comment]
it's caused by 29 api permission, it has been fixed and push to the master branch
