### ISSUE TITLE
File transfer through hotspot

### ISSUE THREAD

**Issue by parasuraam** [CPPAlien/FileTransfer#8]
File transfer through hotspot

This project transfers files through wifi to pc.

I want to sent the files through both wifi and hotspot. 

This shares files with wifi IP.
 

    
    public static String getWifiIp(@NonNull Context context) {
        WifiManager wifimanager = (WifiManager) context.getApplicationContext().getSystemService
                (Context.WIFI_SERVICE);
        if (wifimanager == null) {
            return null;
        }
        WifiInfo wifiInfo = wifimanager.getConnectionInfo();
        if (wifiInfo != null) {
            return intToIp(wifiInfo.getIpAddress());
        }
        return null;
        }

        private static String intToIp(int i) {
        return (i & 0xFF) + "." + ((i >> 8) & 0xFF) + "." + ((i >> 16) & 0xFF) + "." + ((i >> 24)
                & 0xFF);
        }

         public static NetworkInfo.State getWifiConnectState(Context context) {
         ConnectivityManager manager = (ConnectivityManager) context.getSystemService(Context
                .CONNECTIVITY_SERVICE);
        if (manager == null) {
            return NetworkInfo.State.DISCONNECTED;
        }
        NetworkInfo mWiFiNetworkInfo = manager.getNetworkInfo(ConnectivityManager.TYPE_WIFI);
        if (mWiFiNetworkInfo != null) {
            return mWiFiNetworkInfo.getState();
        }
        return NetworkInfo.State.DISCONNECTED;
       }

 
This code used to get the IP address of wifi. I want to share files through both wifi and hotspot. So, I replaced this code to get both wifi and hotspot IP. 

    
    public void getDeviceIpAddress() {
		try {
 
			for (Enumeration<NetworkInterface> enumeration = NetworkInterface
					.getNetworkInterfaces(); enumeration.hasMoreElements();) {
				NetworkInterface networkInterface = enumeration.nextElement();
				for (Enumeration<InetAddress> enumerationIpAddr = networkInterface
						.getInetAddresses(); enumerationIpAddr
						.hasMoreElements();) {
					InetAddress inetAddress = enumerationIpAddr.nextElement();
					if (!inetAddress.isLoopbackAddress()
							&& inetAddress.getAddress().length == 4) {
						tvServerIP.setText(inetAddress.getHostAddress());
					}
				}
			}
		} catch (SocketException e) {
			Log.e("ERROR:", e.toString());
		}
	}

I tried with this code, but it didn't work.

How can I do this?

  [1]: https://github.com/CPPAlien/FileTransfer

**Comment by CPPAlien** [comment]
you mean you cannot get the ip? let me check

**Comment by parasuraam** [comment]
No, I want to transfer the files throughs hotspot. 

How can I do this?

I tried this code to transfer files via hotspot.

    public void getDeviceIpAddress() {
	try {

		for (Enumeration<NetworkInterface> enumeration = NetworkInterface
				.getNetworkInterfaces(); enumeration.hasMoreElements();) {
			NetworkInterface networkInterface = enumeration.nextElement();
			for (Enumeration<InetAddress> enumerationIpAddr = networkInterface
					.getInetAddresses(); enumerationIpAddr
					.hasMoreElements();) {
				InetAddress inetAddress = enumerationIpAddr.nextElement();
				if (!inetAddress.isLoopbackAddress()
						&& inetAddress.getAddress().length == 4) {
					tvServerIP.setText(inetAddress.getHostAddress());
				}
			}
		}
	} catch (SocketException e) {
		Log.e("ERROR:", e.toString());
	}
    }

 But , it failed.

How can I transfer files via hotspot?

**Comment by parasuraam** [comment]
File transfer through hotspot

This project transfers files through wifi to pc.


I want to sent the files through both wifi and hotspot. 



This shares files with wifi IP.
 

    
    public static String getWifiIp(@NonNull Context context) {
        WifiManager wifimanager = (WifiManager) context.getApplicationContext().getSystemService
                (Context.WIFI_SERVICE);
        if (wifimanager == null) {
            return null;
        }
        WifiInfo wifiInfo = wifimanager.getConnectionInfo();
        if (wifiInfo != null) {
            return intToIp(wifiInfo.getIpAddress());
        }
        return null;
        }

        private static String intToIp(int i) {
        return (i & 0xFF) + "." + ((i >> 8) & 0xFF) + "." + ((i >> 16) & 0xFF) + "." + ((i >> 24)
                & 0xFF);
        }

         public static NetworkInfo.State getWifiConnectState(Context context) {
         ConnectivityManager manager = (ConnectivityManager) context.getSystemService(Context
                .CONNECTIVITY_SERVICE);
        if (manager == null) {
            return NetworkInfo.State.DISCONNECTED;
        }
        NetworkInfo mWiFiNetworkInfo = manager.getNetworkInfo(ConnectivityManager.TYPE_WIFI);
        if (mWiFiNetworkInfo != null) {
            return mWiFiNetworkInfo.getState();
        }
        return NetworkInfo.State.DISCONNECTED;
       }




 
This code used to get the IP address of wifi. I want to share files through both wifi and hotspot. So, I replaced this code to get both wifi and hotspot IP. 

    
    public void getDeviceIpAddress() {
		try {
 
			for (Enumeration<NetworkInterface> enumeration = NetworkInterface
					.getNetworkInterfaces(); enumeration.hasMoreElements();) {
				NetworkInterface networkInterface = enumeration.nextElement();
				for (Enumeration<InetAddress> enumerationIpAddr = networkInterface
						.getInetAddresses(); enumerationIpAddr
						.hasMoreElements();) {
					InetAddress inetAddress = enumerationIpAddr.nextElement();
					if (!inetAddress.isLoopbackAddress()
							&& inetAddress.getAddress().length == 4) {
						tvServerIP.setText(inetAddress.getHostAddress());
					}
				}
			}
		} catch (SocketException e) {
			Log.e("ERROR:", e.toString());
		}
	}

I tried with this code, but it didn't work.


How can I do this?



  [1]: https://github.com/CPPAlien/FileTransfer

**Comment by CPPAlien** [comment]
hotspot feature has been supported, Please pull the latest code
